# This is the config script I am using for the MeshADV Mini LoRaWAN/GNSS HAT
# https://github.com/chrismyers2000/MeshAdv-Mini
#
# Note: It may work for others with other SX126X modules without GPS, but I have not tested it.
#       If your board does not have GPS, just comment out the GPS section.
---
Lora:
  Module: sx1262 # Ebyte E22-900M22S
  CS: 8
  IRQ: 16
  Busy: 20
  Reset: 24
  TXen: 12
  DIO2_AS_RF_SWITCH: true
  DIO3_TCXO_VOLTAGE: true

GPS:
# For Pi 5, change the path to this: /dev/ttyAMA0
  SerialPath: /dev/ttyS0

Logging:
  LogLevel: info # debug, info, warn, error
  TraceFile: /var/log/meshtasticd.json
  AsciiLogs: true     # default if not specified is !isatty() on stdout

Webserver:
  Port: 443 # Port for Webserver & Webservices
  RootPath: /usr/share/meshtasticd/web # Root Dir of WebServer

General:
  MaxNodes: 200
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
  MACAddressSource: eth0
